### ISSUE TITLE
playlist not fetching the full list

### ISSUE THREAD

**Issue by sanihaq** [iamsainikhil/trimtube#18]
**Describe the bug**
playlist only fetching first 50 videos in a playlist

**To Reproduce**
use any playlist link with more than 50 videos

**Comment by iamsainikhil** [comment]
@sanihaq above changes were deployed and live now. 

Could you test it and let me know?

**Comment by sanihaq** [comment]
@iamsainikhil working as expected 👍

**Comment by iamsainikhil** [comment]
FYI: The playlist videos will be fetched till 300 videos. I think this is a very good limit keeping localStorage memory in check if the user decides to create a playlist.

Commit -> https://github.com/iamsainikhil/trimtube/commit/cb0885cf2ba050ad143e6a7362b3d87b5c78d20d

cc @sanihaq
