### ISSUE TITLE
using some playlist link leading to error

### ISSUE THREAD

**Issue by sanihaq** [iamsainikhil/trimtube#19]
**Describe the bug**
playlist link like this - https://www.youtube.com/playlist?list=PL9bw4S5ePsEEqCMJSiYZ-KTtEjzVy0YvK not working when pasting in the playlist area. most likely because of this symbol "-".

**Comment by iamsainikhil** [comment]
Oops, you are right!

I updated the regex and it should work now.

https://regex101.com/r/FTaJvI/1

**Comment by iamsainikhil** [comment]
@sanihaq above changes were deployed and live now. 

Could you test it and let me know?

**Comment by sanihaq** [comment]
@iamsainikhil working as expected 👍
